# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20190205_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name_plural': 'evaluaci\xf3nes'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pago_anual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
