# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20190205_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Actividad Comercial'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='identificacion',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='RUC/CEDULA'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedor'),
        ),
    ]
