# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_proveedor_tipo_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='codigo',
            field=models.CharField(max_length=15, null=True, verbose_name='Codigo del Proveedor'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='direccion',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='forma_pago',
            field=models.CharField(choices=[('NC', 'NOTA DE CREDITO'), ('CK', 'CHEQUE'), ('TFI', 'TRANSFERENCIA INTERNACIONAL'), ('TFCI', 'TRANSFERENCIA CUENTA INTEGRA')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='pago_anual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='servicio',
            field=models.CharField(max_length=125, null=True, verbose_name='Servicios Prestados'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='actividad_economica',
            field=models.CharField(max_length=125, null=True, verbose_name='Actividad Comercial'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_cliente',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
