# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_proveedor_tercerizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tercerizacion',
            field=models.PositiveIntegerField(choices=[(1, 'NO'), (2, 'SI')], default=2, null=True, verbose_name='Es tercerizacion?'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tercerizacion',
            field=models.PositiveIntegerField(choices=[(1, 'NO'), (2, 'SI')], default=2, null=True, verbose_name='Es tercerizacion?'),
        ),
    ]
